version: "3.7"
services:
  zoo:
    image: zookeeper:3.4.9
    hostname: zoo
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo:2888:3888
    networks:
      - shortenit

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo
    networks:
      - shortenit

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - shortenit

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=thanhnam.it@gmail.com
      - GF_SMTP_PASSWORD=password
      - GF_SMTP_FROM_ADDRESS=thanhnam.it@gmail.com
    networks:
      - shortenit

  jaeger:
    image: jaegertracing/all-in-one:1.20
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - shortenit

  redisdb:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - shortenit

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
      - 27019:27019
    networks:
      - shortenit

  grpc-alias-provider-v1:
    build:
      dockerfile: $PWD/grpc-alias-provider-v1/Dockerfile
      context: $PWD/grpc-alias-provider-v1/
    environment:
      REDIS_HOST: "redisdb:6379"
      TRACER_COLLECTOR: "http://jaeger:14268/api/traces"
    ports:
      - 50051:50051
    depends_on:
      - redisdb
    networks:
      - shortenit

  api-shortenit-v1:
    build:
      dockerfile: $PWD/api-shortenit-v1/Dockerfile
      context: $PWD/api-shortenit-v1/
    ports:
      - 8085:8085
      - 2222:2222
    depends_on:
      - grpc-alias-provider-v1
      - mongodb
      - jaeger
      - kafka
    environment:
      APP_NAME: "api-shortenit-v1"
      TRACER_NAME: "api-shortenit-v1"
      TRACER_COLLECTOR: "http://jaeger:14268/api/traces"
      ALIAS_CON: "grpc-alias-provider-v1:50051"
      MONGO_CON: "mongodb://mongodb:27017/"
      PORT: 8085
      KAFKA_PEERS: "kafka:19092"
      GETURL_EVENT_TOPIC: "geturl-event-topic"
      GOFLAGS: "-mod=vendor"
      COMMIT: $COMMIT_SHA
    networks:
      - shortenit

volumes:
  prometheus-data:

networks:
  shortenit: