{
 "title": "OpenTelemetry",
 "time": { "from": "2021-02-14T22:48:53.329Z", "to": "2021-02-14T23:10:55.165Z" },
 "panels": [
  {
   "title": "Request Size Total",
   "type": "graph",
   "description": "rate(api_shortenit_v1_create_alias_request_size_total[5m])",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(api_shortenit_v1_create_alias_request_size_total[5m])",
     "legendFormat": "rate(api_shortenit_v1_create_alias_request_size_total[5m])"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(api_shortenit_v1_latency_sum[6m]) / rate(api_shortenit_v1_latency_count[6m])"
    }
   ]
  },
  {
   "title": "GC Count Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(runtime_go_gc_count[5m])" }
   ]
  },
  {
   "title": "Histogram  GET /shortenit/{alias}",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_shortenit_v1_latency_bucket{operation=\"GET /shortenit/{alias}\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Event Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_shortenit_v1_kafka_queue_size"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_shortenit_v1_latency_bucket{le=\"10000\"}[6m])) by(operation) / sum(rate(api_shortenit_v1_latency_bucket[6m])) by (operation)"
    }
   ]
  }
 ]
}