// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: proto/alias/v1/alias.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetNewAliasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNewAliasRequest) Reset() {
	*x = GetNewAliasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alias_v1_alias_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewAliasRequest) ProtoMessage() {}

func (x *GetNewAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alias_v1_alias_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewAliasRequest.ProtoReflect.Descriptor instead.
func (*GetNewAliasRequest) Descriptor() ([]byte, []int) {
	return file_proto_alias_v1_alias_proto_rawDescGZIP(), []int{0}
}

type GetNewAliasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias     string `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Timestamp uint64 `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GetNewAliasResponse) Reset() {
	*x = GetNewAliasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alias_v1_alias_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewAliasResponse) ProtoMessage() {}

func (x *GetNewAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alias_v1_alias_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewAliasResponse.ProtoReflect.Descriptor instead.
func (*GetNewAliasResponse) Descriptor() ([]byte, []int) {
	return file_proto_alias_v1_alias_proto_rawDescGZIP(), []int{1}
}

func (x *GetNewAliasResponse) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *GetNewAliasResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CheckAliasValidityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias string `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *CheckAliasValidityRequest) Reset() {
	*x = CheckAliasValidityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alias_v1_alias_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAliasValidityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAliasValidityRequest) ProtoMessage() {}

func (x *CheckAliasValidityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alias_v1_alias_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAliasValidityRequest.ProtoReflect.Descriptor instead.
func (*CheckAliasValidityRequest) Descriptor() ([]byte, []int) {
	return file_proto_alias_v1_alias_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAliasValidityRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type CheckAliasValidityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *CheckAliasValidityResponse) Reset() {
	*x = CheckAliasValidityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_alias_v1_alias_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAliasValidityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAliasValidityResponse) ProtoMessage() {}

func (x *CheckAliasValidityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alias_v1_alias_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAliasValidityResponse.ProtoReflect.Descriptor instead.
func (*CheckAliasValidityResponse) Descriptor() ([]byte, []int) {
	return file_proto_alias_v1_alias_proto_rawDescGZIP(), []int{3}
}

func (x *CheckAliasValidityResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_alias_v1_alias_proto protoreflect.FileDescriptor

var file_proto_alias_v1_alias_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31,
	0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c,
	0x69, 0x61, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x31, 0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61,
	0x6c, 0x69, 0x61, 0x73, 0x22, 0x32, 0x0a, 0x1a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x32, 0xaf, 0x01, 0x0a, 0x14, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x40, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x69, 0x61, 0x73,
	0x12, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x85, 0x01, 0x0a, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x74, 0x68, 0x61, 0x6e, 0x68, 0x6e,
	0x61, 0x6d, 0x69, 0x74, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x69, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x41,
	0x6c, 0x69, 0x61, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x45, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x61, 0x6e, 0x68, 0x6e, 0x61, 0x6d,
	0x69, 0x74, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x69, 0x74, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x2d, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_alias_v1_alias_proto_rawDescOnce sync.Once
	file_proto_alias_v1_alias_proto_rawDescData = file_proto_alias_v1_alias_proto_rawDesc
)

func file_proto_alias_v1_alias_proto_rawDescGZIP() []byte {
	file_proto_alias_v1_alias_proto_rawDescOnce.Do(func() {
		file_proto_alias_v1_alias_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_alias_v1_alias_proto_rawDescData)
	})
	return file_proto_alias_v1_alias_proto_rawDescData
}

var file_proto_alias_v1_alias_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_alias_v1_alias_proto_goTypes = []interface{}{
	(*GetNewAliasRequest)(nil),         // 0: v1.GetNewAliasRequest
	(*GetNewAliasResponse)(nil),        // 1: v1.GetNewAliasResponse
	(*CheckAliasValidityRequest)(nil),  // 2: v1.CheckAliasValidityRequest
	(*CheckAliasValidityResponse)(nil), // 3: v1.CheckAliasValidityResponse
}
var file_proto_alias_v1_alias_proto_depIdxs = []int32{
	0, // 0: v1.AliasProviderService.GetNewAlias:input_type -> v1.GetNewAliasRequest
	2, // 1: v1.AliasProviderService.CheckAliasValidity:input_type -> v1.CheckAliasValidityRequest
	1, // 2: v1.AliasProviderService.GetNewAlias:output_type -> v1.GetNewAliasResponse
	3, // 3: v1.AliasProviderService.CheckAliasValidity:output_type -> v1.CheckAliasValidityResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_alias_v1_alias_proto_init() }
func file_proto_alias_v1_alias_proto_init() {
	if File_proto_alias_v1_alias_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_alias_v1_alias_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewAliasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alias_v1_alias_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewAliasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alias_v1_alias_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAliasValidityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alias_v1_alias_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAliasValidityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_alias_v1_alias_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_alias_v1_alias_proto_goTypes,
		DependencyIndexes: file_proto_alias_v1_alias_proto_depIdxs,
		MessageInfos:      file_proto_alias_v1_alias_proto_msgTypes,
	}.Build()
	File_proto_alias_v1_alias_proto = out.File
	file_proto_alias_v1_alias_proto_rawDesc = nil
	file_proto_alias_v1_alias_proto_goTypes = nil
	file_proto_alias_v1_alias_proto_depIdxs = nil
}
